package utilities.equipment.modifikators;

public enum Modifikators {
    BASEPLUSONE, BASEPLUSTWO, BASELUSTHREE, HPPLUSONE, HPPLUSTWO, HPPLUSTHREE,
    STRPLUSONE, STRPLUSTWO, STRPLUSTHREE, INTPLUSONE, INTPLUSTWO, INTPLUSTHREE,
    DEXPLUSONE, DEXPLUSTWO, DEXPLUSTHREE
}
